const PAGE_NOT_FOUND = 404;
const INVALID_DATA = 400;
const UNAUTHORIZED = 401;
const SERVER_ERROR = 500;
const CONFLICT_ERROR = 409;

module.exports = {
  PAGE_NOT_FOUND,
  INVALID_DATA,
  SERVER_ERROR,
  CONFLICT_ERROR,
  UNAUTHORIZED,
};
